os:
  - linux
  - osx

language: go
go:
  - 1.14

env:
  - GO111MODULE=on
    go_import_path: github.com/ohler55/ojg

install:
- go get github.com/mattn/goveralls

script:
  - set -e
  - go test -i ./...
  - go test ./...
  - go test -race -coverprofile=./cov.out  ./...
  - $HOME/gopath/bin/goveralls -repotoken t2TmOT2IIY7dLqAxhiyOoManIEpVx3z5m -coverprofile=./cov.out -service travis-ci
  - set +e
